### ISSUE TITLE
Performance Drops?

### ISSUE THREAD

**Issue by RealHiDevin** [bhamon/gpuPlotGenerator#22] opened 2017-06-27 22:40 UTC
Here's my setup. rx 480 4gb I'm plotting in direct.
devices.txt ( 0 0 8192 256 4 ) 
On SMR Drive goes from, 40k nonces - 2k nonces after 1 hour 
On SSD Drive goes from 40k nonces - 6k nonces after 1 hour
Is there something wrong here?

edit: I only use ~5gb of ram since I only have 8gb of ram while creating the plot.

**Comment by disrvptor** [comment] 2017-06-28 10:44
I've noticed the same issue. It's generally faster to generate using buffer then run an optimizer after.

**Comment by bhamon** [comment] 2017-06-30 06:34
Which version do you use? If you use the latest release, did you launch it with admin rights?

About the nonces/min computation, it tends to be more accurate at the end of the process rather than at the beginning as it is roughly `noncesComputed / timeElapsed` with gaps between refreshes.

Also, please note that the `direct` writing strategy is really disk intensive and, depending on your hardware and OS, may just be inappropriate. It is commonly better with a large amount of RAM (32GB+).

**Comment by RealHiDevin** [comment] 2017-06-30 22:51
Used the latest release with admin rights.

" Also, please note that the direct writing strategy is really disk intensive and, depending on your hardware and OS, may just be inappropriate. It is commonly better with a large amount of RAM (32GB+). "

I see that this is true, but why can my CPU run faster than gpuplotgenerator overtime, which I don't get :(
On the forums, Luxe can get a constant 20k nonces with his rx 480 but he's using 27GB of RAM

In Luxe testing, he said "102400 to use 25GB of RAM (using ~6,25GB RAM reduces my nonces/minute by 25% ) " 

Reason im confused is that my CPU is plotting faster than my GPU over time ~ 5000 nonces a minute, compared to 2000 nonces a minute on gpuPlotGenerator and im using the same amount of ram for each :/

**Comment by blinkin69** [comment] 2017-07-05 11:08
i have very good performance when i use direct mode on SSD with 8 GB RAM and then file copy to my SMR usb disks.

my plot time is ~40000nounce/sec ! include copytime to SMR because i can do write and read on the SSD at the same time without performance drop.

i use version -4.0.3 

but the bad think is that my SSD has only 500 GB space. i need some automation

plot -> copy -> delete file -> -> change nounce in config -> plot -> copy - delete file ....

dont know if i can script that

**Comment by bhamon** [comment] 2018-01-14 20:58
@RealHiDevin Have you found a solution about your issue? It seems really hardware related to me.

**Comment by MircoBlitz** [comment] 2018-01-15 13:01
I have the exact same issue with my 8TB Segate Archive drives. 
Although they perform well in buffered mode, writing in direct mode the perfomance drops drastic from around 40k to 1k nounces/min (GTX1080 utilized by 100% in the beginning, then dropping to about 5%).
What I noticed, in buffered mode, iotop shows a max bandwidth of 112MB/s and in direct 10MB/s and not an inch more. This looks like an I/O-Cache/NonCache issue to me.

All my drives I'd like to plot show exactly the same behaviour. So I'd automate with a buffered -> optimize -> repeat script. But I'd love to go direct and burst a complete drive in one go (which effects the read time later drastic, around 15% difference in 1 single big file vs 16 500MB files)

**Comment by bhamon** [comment] 2018-01-15 13:31
@MircoBlitz Plotting to a mechanical drive is slower in direct mode than in buffered mode. The direct mode is really write intensive on the disk so you can't expect it to be as fast as a the buffered mode. Even the buffered+optimization strategy can be faster as it's more efficient by design for historical contiguous memory mapping.

The only decent configuration for a `direct` plotting strategy is to use a SSD. Even in this configuration it's highly recommended to launch the plotter in admin mode to prevent 0-filling which slows down the writing of the first plot.

I kept this issue open to try to correct the lag effect on the ETA computation, but haven't found a solution yet.

**Comment by bhamon** [comment] 2018-02-28 14:01
Still no idea on how to accurately correct the lag effect.
As it's only a display improvement I'll close it.

**Closed by bhamon** 2018-02-28 14:01 UTC
