### ISSUE TITLE
[ERROR] Unable to prevent zero filling

### ISSUE THREAD

**Issue by jxer** [bhamon/gpuPlotGenerator#20] opened 2017-06-18 00:39 UTC
gpuPlotGenerator.exe generate direct w:\9515785206432086504_3747841_5734400_4096
-------------------------
GPU plot generator v4.1.0
-------------------------
Author:   Cryo
Bitcoin:  138gMBhCrNkbaiTCmUhP9HLU9xwn5QKZgD
Burst:    BURST-YA29-QCEW-QXC3-BKXDL
----
Loading platforms...
Loading devices...
Loading devices configurations...
Initializing generation devices...
    [0] Device: Baffin (OpenCL 2.0 AMD-APP (2348.3))
    [0] Device memory: 2GB 0MB
    [0] CPU memory: 2GB 0MB
Initializing generation contexts...

[ERROR] Unable to prevent zero filling
_______________________________________________________________________

gpuPlotGenerator-bin-win-x64-4.0.3>gpuPlotGenerator
exe generate direct w:\9515785206432086504_3747841_5734400_4096
-------------------------
GPU plot generator v4.0.3
-------------------------
Author:   Cryo
Bitcoin:  138gMBhCrNkbaiTCmUhP9HLU9xwn5QKZgD
Burst:    BURST-YA29-QCEW-QXC3-BKXDL
----
Loading platforms...
Loading devices...
Loading devices configurations...
Initializing generation devices...
    [0] Device: Baffin (OpenCL 2.0 AMD-APP (2348.3))
    [0] Device memory: 2GB 0MB
    [0] CPU memory: 2GB 0MB
Initializing generation contexts...
    [0] Path: w:/9515785206432086504_3747841_5734400_5734400
    [0] Nonces: 3747841 to 9482240 (1TB 376GB 0MB)
    [0] CPU memory: 1GB 0MB
----
Devices number: 1
Plots files number: 1
Total nonces number: 5734400
CPU memory: 3GB 0MB
----
Generating nonces...
0.00% (0/5734400 remaining nonces), 0.00 nonces/minutes, ETA: 10y 48w 6d 5h 20m

0.00% (0/5734400 remaining nonces), 0.00 nonces/minutes, ETA: 10y 48w 6d 5h 20m

0.00% (0/5734400 remaining nonces), 0.00 nonces/minutes, ETA: 10y 48w 6d 5h 20m

0.00% (0/5734400 remaining nonces), 0.00 nonces/minutes, ETA: 10y 48w 6d 5h 20m
0s...

**Comment by bhamon** [comment] 2017-06-18 01:09
@jxer Can you retry with the new 4.1.1 version so that I can have the underlying Windows error code.

**Comment by jxer** [comment] 2017-06-18 01:23
gpuPlotGenerator-bin-win-x64-4.1.1>gpuPlotGenerator.
exe generate direct w:\9515785206432086504_3747841_5734400_4096
-------------------------
GPU plot generator v4.1.1
-------------------------
Author:   Cryo
Bitcoin:  138gMBhCrNkbaiTCmUhP9HLU9xwn5QKZgD
Burst:    BURST-YA29-QCEW-QXC3-BKXDL
----
Loading platforms...
Loading devices...
Loading devices configurations...
Initializing generation devices...
    [0] Device: Baffin (OpenCL 2.0 AMD-APP (2348.3))
    [0] Device memory: 2GB 0MB
    [0] CPU memory: 2GB 0MB
Initializing generation contexts...

[ERROR] Unable to prevent zero filling: 87

**Comment by jxer** [comment] 2017-06-18 01:25
http://i.imgur.com/C0J6S6R.png

**Comment by bhamon** [comment] 2017-06-18 01:28
Have you picked the x86 or the x64 version?

**Comment by jxer** [comment] 2017-06-18 01:28
"gpuPlotGenerator-bin-win-x64-4.1.1>gpuPlotGenerator.
exe generate direct w:\9515785206432086504_3747841_5734400_4096"

**Comment by bhamon** [comment] 2017-06-18 01:35
@jxer The error code 87 is for "Invalid param", so lets check it: https://mega.nz/#!vNsiGZJZ!LrddYAfc--sdEQ99xs8SkwEQJESE7ow-hIKLpxgmu4E

**Comment by jxer** [comment] 2017-06-18 01:40
gpuPlotGenerator-bin-win-x64-4.1.2a>gpuPlotGenerator
.exe generate direct w:\9515785206432086504_3747841_5734400_4096
--------------------------
GPU plot generator v4.1.2a
--------------------------
Author:   Cryo
Bitcoin:  138gMBhCrNkbaiTCmUhP9HLU9xwn5QKZgD
Burst:    BURST-YA29-QCEW-QXC3-BKXDL
----
Loading platforms...
Loading devices...
Loading devices configurations...
Initializing generation devices...
    [0] Device: Baffin (OpenCL 2.0 AMD-APP (2348.3))
    [0] Device memory: 2GB 0MB
    [0] CPU memory: 2GB 0MB
Initializing generation contexts...

[ERROR] Unable to prevent zero filling: 87 (1503238553600)

**Comment by bhamon** [comment] 2017-06-18 01:45
@jxer The value seems good to me. Also I can't reproduce on my computer...

**Comment by bhamon** [comment] 2017-06-18 01:51
@jxer Do you have enough contigous space on your disk to plot that file? Can you try with a smaller size?

**Comment by jxer** [comment] 2017-06-18 01:53
its plots fine on 4.0.3

**Comment by bhamon** [comment] 2017-06-18 01:57
@jxer Yes, but there is no pre-allocation on 4.0.3 for the direct writing strategy. So the output file can be heavily fragmented (sparse file). You can use a defragmentation tool to see the physical state of your drive.

**Comment by jxer** [comment] 2017-06-18 02:01
your expectation is a 0 disk? the drive is empty its a 2tb drive

**Comment by bhamon** [comment] 2017-06-18 02:09
@jxer I've searched everywhere without luck. On [burst-team](https://forums.burst-team.us/search?term=error%2087&in=titlesposts) someone experienced the same error as you.
What file system do you use? NTFS? FAT32? ExFAT?

**Comment by jxer** [comment] 2017-06-18 02:20
Ext4 over cifs

**Comment by bhamon** [comment] 2017-06-18 02:37
@jxer Ok, that could be the root cause. Your setup is a bit tricky.
You should consider plotting in direct mode on local disks (500GB SSDs are great for that) then transferring the resulting files to the remote disks afterwards.

**Closed** 2017-06-30 06:39 UTC
